name: Node.js library CI

# Triggers the workflow on push or pull request events
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: make

    - name: Lint
      run: make lint

    - name: Run tests
      run: make ci

    - name: Report test coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Security audit
      uses: snyk/actions@0.3.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
